# =================================== #
# compile_image.yml                   #
# nyxbot's new distribution workflow  #
# =================================== #

# Define Name
name: Image Compiler

# Description:
#   This actions workflow was designed to compile our image and upload it to
#   the Github Container Registry. It also shells into our server and tells
#   it to update.

#
# ===== [ Triggers ] ==========================================================
#

# NOTE: Originally this was supposed to have an 'on_workflow' trigger so it
#       would only run after test passes. However there was no reliable way
#       to test this, so I ditched it. Now it just runs on tagged releases.

on:
  push:
    tags:
    - '*'

#
# ===== [ Jobs ] ==============================================================
#

jobs:

  # 1.) Build Script
  build:
    name: Build Docker Image & Upload
    runs-on: ubuntu-latest
    steps:

    # 1.1.) Set up workspace
    - name: Set up workspace
      uses: actions/checkout@v1

    # 1.2) Auth with GHCR
    - name: Authenticate with GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GH_USERNAME }}
        password: ${{ secrets.GH_TOKEN }}

    # 1.3) Set up QEMU for arm64 compilation
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    # 1.4) Set up Docker build
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # 1.5) Build and Push
    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        push: true
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        tags: ghcr.io/azure-agst/nyxbot:latest
